### ISSUE TITLE
Don't allow cluster-names that don't comply with DNS spec

### ISSUE THREAD

**Issue by thekad** [openshift/openshift-azure#1116]
Our FakeRP doesn't validate the name of the cluster for dots and other non DNS spec compliant characters, which may lead to unintended consequences.
Investigate if this is also a problem with RealRP.

**Comment by mjudeikis** [comment]
only in our fakeRP code. not a GA issue.

**Comment by jim-minter** [comment]
@ehashman please review which fields of OpenShiftManagedCluster are externally writeable but are not currently well validated by us - examples: Name, Location, Tags.  Dig out what the standard Azure validation regexes for these fields are and add them - really, this is belt and braces because MSFT should be doing this already; the aim is loose enough so that we don't trip ourselves up, but tight enough that people can't squirrel away naughty values in there.

**Comment by ehashman** [comment]
- Azure docs suggest the regex `^[a-z][a-z0-9-]{1,61}[a-z0-9]$` for a domain name label: https://docs.microsoft.com/en-us/azure/azure-resource-manager/template-best-practices#resources
- Locations appear to be attached per RG, not sure how much effort we want to put into validating this (most of the templating examples I've found populate these values dynamically).
- Tag policy is relatively long and complex, dunno how much of it we want to enforce: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags

**Comment by ehashman** [comment]
We currently validate that name and location are non-empty: https://github.com/openshift/openshift-azure/blob/ccf8397a916173471a802d8703b2e7baecd4b981/pkg/api/validate/validators.go#L18-L24

Unclear if there's much value in adding a bunch of validation for tags.

I'll start with a PR to improve name validation and we can go from there.
