### ISSUE TITLE
Scale cluster deployed using old version of the plugin failing

### ISSUE THREAD

**Issue by julienstroheker** [openshift/openshift-azure#1334]
When i'm trying to scale an old cluster deployed with plugin release `v3.0` using `v3.2` release I'm having the following message : 

```
{
    "code": "BadRequest",
    "message": "An error has occurred in subscription XXXXXXXX, resourceGroup: julientest1000 request: [cluster with version \"v0.0\" cannot be updated by resource provider with version \"v3.2\"]."
}
```

**Comment by jim-minter** [comment]
The general error is expected because the cluster was not built with v3.2.

The fact that the old cluster is reporting version "v0.0" is a little unexpected; I think it is almost certainly because you originally built that cluster vendoring a point-in-time commit of master.

When you did that, we were setting version to v0.0 in pluginconfig-311.yaml in master, so that's how that text got there.

When we make an official release, we change the "v0.0" in that file to the actual release version.

So I don't think there's actually an issue here.

However, I am worried about the complexity of ensuring that the plugin is correctly configured in production - please could you bring up that topic for discussion on Monday?

**Comment by jim-minter** [comment]
believe this can be closed, @julienstroheker please reopen if not
