### ISSUE TITLE
v3.2 -> v4 upgrade fail

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1350]
Sync pod fails to run after node rotation: 

```
time="2019-03-26T13:31:28Z" level=info msg="s.getBlob: [invalid properties.masterPoolProfile.vmSize \"Standard_D2s_v3\", invalid properties.agentPoolProfiles[\"infra\"].vmSize \"Standard_D2s_v3\", invalid properties.agentPoolProfiles[\"compute\"].vmSize \"Standard_D2s_v3\"]"
time="2019-03-26T13:34:27Z" level=info msg="fetching config blob"
time="2019-03-26T13:34:27Z" level=info msg="enriching config blob"
time="2019-03-26T13:34:28Z" level=info msg="s.getBlob: [invalid properties.masterPoolProfile.vmSize \"Standard_D2s_v3\", invalid properties.agentPoolProfiles[\"infra\"].vmSize \"Standard_D2s_v3\", invalid properties.agentPoolProfiles[\"compute\"].vmSize \"Standard_D2s_v3\"]"
```

/kind bug

**Comment by jim-minter** [comment]
doh!

This is caused as follows:
* deploy v3.2 cluster using v3.2 codebase - works
* logic error: upgrade-e2e.sh does not actually request a cluster upgrade, so one does not take place
* redeploy v3.2 cluster using v4.0 codebase - fails because v3.2 sync pod fails to validate because RunningUnderTest has been removed from the config blob in v4.0 - another logic error

both of these are good catches, will fix.
