### ISSUE TITLE
[proposal] move TestConfig into Ctx

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1598]
Passing `testConfig` around the place as a parameter is not very flexible. In addition, if we want to wire it to a new place, it requires a lot of changes (example https://github.com/openshift/openshift-azure/pull/1590).

Suggestion to move TestConfig into ctx:
```
ContextTestConfig ContextKey = "TestConfig"

// testConfig is used to orchestrate additional debugging
// should not be used in Production
testConfig := GetTestConfig()
ctx = context.WithValue(ctx, TestConfig, testConfig)
```

This way we can use it everywhere, where we need it.

After this there is 2 ways to implement this:
1. Make all `xNew(ctx context.Context)` object to accept context, and parse the structure:
```
// NewAPIValidator return instance of external API validator
func NewAPIValidator(ctx context.Context) *APIValidator {
	tc := ctx.Value(api.ContextTestConfig).(api.TestConfig)
	return &APIValidator{runningUnderTest: tc.RunningUnderTest}
}
```
2. Make New agnositic and pass ctx to all methods of the interface:
```
// Validate validates a OpenShiftManagedCluster struct
func (v *APIValidator) Validate(ctx context.Context, cs, oldCs *api.OpenShiftManagedCluster, externalOnly bool) (errs []error) {
	if cs == nil {
		errs = append(errs, fmt.Errorf("cs cannot be nil"))
		return
	}
....
```
1st requires less code changes, but it looks strange as we are passing ctx to `New` method. 
2nd requires more code changes, but now all methods would have ctx in the args and we can re-use it later too.

In example validate now would look like this:
```
validate.NewAPIValidator(p.testConfig.RunningUnderTest) -> validate.NewAPIValidator()
...
_, err := p.configInterfaceFactory(new, p.testConfig.RunningUnderTest)
_, err := p.configInterfaceFactory(ctx, new)
```

All this change should be done with the removal of `v3.2` due how code is structured around differences in `v3.2->v4.2`.

@jim-minter @openshift/sig-azure WDYT?

**Comment by jim-minter** [comment]
We should consider testConfig along with all the other arguments we habitually pass around the place, but we should also accept that different solutions may be appropriate for each.

I think we're doing well cutting down long argument lists for non-New functions by making cs and log struct members - we should continue this drive.  I'm not so worried about New functions.  Usability-wise, for cs and log I think that is the right direction rather than adding either to the context (I know you weren't suggesting doing that).

I am actually wondering whether a singleton TestConfig global in its own package (populated once at process startup) would make sense for this use case - or is that too disgusting for words?  It's basically the same as an environment variable, just with a little more control over how it's populated -- which is basically what TestConfig is anyway.

Thoughts?

**Comment by mjudeikis** [comment]
The idea behind `TestConfig` being in the context was that it would be not exposed to MSFT in anyways. At the moment it is passed as `nil` value into certain functions. If we move it to the context, it will not be directly exposed as a parameter at all.

I agree cs and log being members of the package structs, so this way simplifying the parameters list. If we apply same for the `TestConfig` it still exists as a parameter in `xNew` functions. So Im not a fan of this.

When it comes having test config as a separate package with global expose - this does not sound very bad, if we limit the use of it. And it might look better than having it in the context (less casting and checking). 

In the end I want `TestConfig` to be gone from all function parameters and available globally. So global package or ctx is only feasible ways. Am I right thinking your vote is for a global package over context?
