### ISSUE TITLE
could not update aad app: ... One or more properties contains invalid values

### ISSUE THREAD

**Issue by ehashman** [openshift/openshift-azure#2234]
```
ime="2020-02-18T17:52:12Z" level=fatal msg="could not update aad app: graphrbac.ApplicationsClient#Patch: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"Unknown\" Message=\"Unknown service error\" Details=[{\"odata.error\":{\"code\":\"Request_BadRequest\",\"date\":\"2020-02-18T17:52:12\",\"message\":{\"lang\":\"en\",\"value\":\"One or more properties contains invalid values.\"},\"requestId\":\"6e7e8b07-a97b-48c3-91b9-98e02eaf916a\"}}]"
```

/kind bug

This appears to be cropping up all over CI. See #2231 #2233.

**Comment by olga-mir** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2235/pull-ci-azure-master-upgrade-v12.2/396/build-log.txt

https://github.com/openshift/openshift-azure/pull/2235

**Comment by olga-mir** [comment]
describing aad object to which we link our CI clusters I can see it reached 256 links in `replyUrls` section which is the limit https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url:
```
$ az ad app show --id <id> > aad-obj.json
$ jq '.replyUrls|length' aad-obj.json 
256
```

The error wording doesn't seem to be pointing in this direction, however even if this is not a root cause it is still an issue that we have to take care of. Also this can explain why 100% (at least it seems like 100%) CI tests fail, while creating dev test clusters works fine.

@mjudeikis @ehashman
