### ISSUE TITLE
log package panic

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#299]
If I use our `log` package w/o calling `New` to initialize the logger, when I use one of the logging fns, they will panic. Not sure that's expected behavior.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d08d4]

goroutine 6 [running]:
testing.tRunner.func1(0xc4203560f0)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0xe77b80, 0x1660bf0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/openshift/openshift-azure/pkg/log.Debug(0xc420075c80, 0x1, 0x1)
	/go/src/github.com/openshift/openshift-azure/pkg/log/log.go:44 +0x24
```
@openshift/sig-azure

**Comment by mjudeikis** [comment]
No its not. Interesting... Where do you see this?

**Comment by kargakis** [comment]
I saw it in one of my PRs where I tried to use `log` in cmd/createorupdate/update.go.

Should be easy to reproduce.

**Comment by kargakis** [comment]
Interestingly log is already used in that level, so it may also be a nil pointer exception of what I was trying to print :$

**Comment by pweil-** [comment]
> Interestingly log is already used in that level, so it may also be a nil pointer exception of what I was trying to print :$

yeah, there is still the issue if the plugin isn't initialized where any call to the log package would NPE.  We should probably just call `New` in each method with a default logger since if it's already initialized it won't have effect.  Then again I think that may make the plugin method misleading since it won't *actually* give you the logger you wanted.  All of this for an easier api, starting to wonder if it was worth it :smile:

**Comment by kargakis** [comment]
Worth cleaning it up.

**Comment by kargakis** [comment]
Hrm, after spending some time on reviewing what we have I am not sure this can be cleaned up easily. All of our plugin methods are using `New` so we should be covered inside the plugin code.
