### ISSUE TITLE
Disable and enable/kick sync pod as part of the upgrade process

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#333]

**Comment by mjudeikis** [comment]
Or sync pod needs to read labels on the nodes and act on them. Similar to how coreos self-updatable stack works. Ticket to update is handled by labels.

**Comment by kargakis** [comment]
I know we discussed this before but tbh I don't feel strong about this, it's one more thing to care about during an upgrade. I think I would prefer we do partial validation based on the config version. Also if we want to guarantee a unique version of the sync pod is always running we should be using a statefulset instead of a deployment (belts and suspenders).

**Comment by jim-minter** [comment]
I can think of 2 cases of interest here:
1- at the end of an update, knowing the sync pod has run with an updated config before releasing a cluster back to the user
2- preventing the sync pod from making things unexpectedly confusing during major version upgrade.

**Comment by kargakis** [comment]
>  1- at the end of an update, knowing the sync pod has run with an updated config before releasing a cluster back to the user

I don't think this is achieved by scaling up and down. A running pod is not a guarantee that sync applied changes to a cluster.

**Comment by asalkeld** [comment]
couldn't we just run sync as a cron job so that 
1. it exits after one iteration
2. every time it starts, it uses the correct image
3. you can run it manually at update

**Comment by mjudeikis** [comment]
@asalkeld this implies api server and controller is alive and ready. And without a first run of sync pod - I don't think it is. A hybrid could be: run sync pod once at startup, and later hand over operations to cronjob?
