### ISSUE TITLE
Consider adding oldCs in all plugin fn signatures

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#342]
@openshift/sig-azure 

Tagging for PP, but up for discussion whether we need it.

**Comment by jim-minter** [comment]
what's the reasoning for needing this?

**Comment by kargakis** [comment]
Brought up in https://github.com/openshift/openshift-azure/pull/341#pullrequestreview-152469143

I think I lean more towards adding it when we need it. Our interface signatures do not contain unused fields and MSFT will need to revendor anyway if we add it in signatures today and eventually use it a month from today.

**Comment by pweil-** [comment]
It was mentioned mostly because we're seeing more things that require "do X if it's an update" and `oldCs` is our only indication of an update.  Really the only thing I see it not on that it might be useful is `GenerateConfig`.  I can't think of a need for it on `InitializeCluster`, `HealthCheck`, `Drain`, or `WaitForReady`.

Seems like if we're doing the revendor dance a lot it might be easy to add in but no argument against waiting until it's required - maybe it never is.

**Comment by kargakis** [comment]
> Seems like if we're doing the revendor dance a lot it might be easy to add in but no argument against waiting until it's required - maybe it never is.

Yeah, let's get this off our radar for now and worry about it when we will need to add it.
