### ISSUE TITLE
MergeConfig overwrites existing model

### ISSUE THREAD

**Issue by sozercan** [openshift/openshift-azure#434]
In an` PUT` (update) operation, if user sends in a partial request such as the basic `routerProfile` below:

```
...
	  "routerProfiles": [
		  {
			  "name": "default"
		  }
	  ]
...
```

This will override the existing fields like `publicSubdomain` and `fqdn`, since it will skip copying because `len(cs.Properties.RouterProfiles)` will not be 0.
https://github.com/openshift/openshift-azure/blob/master/pkg/plugin/plugin.go#L55
This issue applies to other properties such as `AgentPoolProfiles` as well.

It might be better to take the existing saved model and update it rather then trying to constructing a new one based on the old model.

**Comment by kargakis** [comment]
Question: how do we want to merge the following request:
```
	  "routerProfiles": [
		  {
			  "publicSubdomain": "foo.router"
		  }
	  ]
```
We invalidate a missing name from a routerProfile but validation runs after we merge so if we are merging on top of a pre-existing slice with a single profile, should we merge the above request? What happens when there are multiple pre-existing profiles?

Similar question for AgentPoolProfile.

**Comment by kargakis** [comment]
> Similar question for AgentPoolProfile.

I guess for AgentPoolProfiles the answer is slightly more obvious: since we already use multiple profiles, we cannot really merge requests with missing names. How can we invalidate these requests though if merging runs first? Should our merge function let us know it failed to merge something? Then how do we return a user friendly error? Does validation need to run at all in that case?
