### ISSUE TITLE
calculate ose container image versions from vm image version

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#452]
follow-up from #415 

`v := "v3.10.14" // TODO: perhaps we should calculate this from c.ImageVersion`

**Comment by radlinskii** [comment]
Hello, I found this issue because of the label you put onto it. This is literally my first open-source issue. I would like it to be assigned to me. I'm not sure how to calculate the right version from `c.ImageVersion` though. `c.ImageVersion` is a string with pattern `310.34.20180913`. I'm guessing last 8 characters represents the date which leaves me with image version `310.34`. I need to turn it to `3.10.34`, did I got it right?

**Comment by jim-minter** [comment]
Hi @radlinskii thanks for your interest.  Your contributions are welcome, although bear in mind that you may have difficulties testing because even though this code base is open source right now there are no publicly available images which can be used for test.  Also on this occasion we needed to push forwards with fixing this particular issue due to our timescales.  If you're interested in working on other "good first issues" feel free to and we'll try to take on related PRs that you send.  Thanks!

**Comment by jim-minter** [comment]
fixed by #468
