### ISSUE TITLE
Returning vnet name

### ISSUE THREAD

**Issue by sozercan** [openshift/openshift-azure#544]
It might be good to return the full virtual network name, so CLI or other clients can initiate peering using this value.

cc @amanohar

**Comment by jim-minter** [comment]
copy/paste from @amanohar on slack:

For the custom VNET peering case rIght now RP has hard coded value of VNET name that OSA plugin creates to be used during peering.

I have 2 concerns with RP's approach of using a hard value to create peering:
1) Since OSA plugin is creating the VNET I think this VNET should also be set in the internal data model (unversioned data model) along with customer provided VNET id. That way RP can use it for peering and the name can change over time with no back compat issues.
2) #1 is easily solvable. However CLI will also need to hard code the VNET name to do peering which is not ideal.

With #2 in mind, imo it makes sense to expose OSA created VNET in the public data model. This will help customers who are not using CLI to get the VNET name from the public data model and do peering themselves (customers also don't know the name of the AMA resource group).

Otherwise, Portal and ARM template deployment experience will not be good as customer won't know where to get the VNET name from.

Thoughts?  (both points are not PP blocking).

**Comment by asalkeld** [comment]
@jim-minter so there is also #543  issue. Do we need a GetClusterInfo() function in the Plugin API that returns these attributes below?

- VNET name
- config container
- blob name

**Comment by jim-minter** [comment]
no - these things are separate.

**Comment by jim-minter** [comment]
suggest a field called VnetID under NetworkProfile (include Godoc documentation please).  Will need to make changes in all 3 APIs, and converters, and unit tests, and write the field value probably somewhere under `(p *plugin) CreateOrUpdate`

as part of this work, please look at our unit test coverage for API type sync - are there areas in which you could theoretically make invalid changes to our API structs that made them out of sync, which would not be caught by our unit testing?
