### ISSUE TITLE
lack RUNNING_UNDER_TEST=true breaks local create

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#669]
Lack of `RUNNING_UNDER_TEST=true` makes cluster creation to fail

**Comment by kwoodson** [comment]
When setting `RUNNING_UNDER_TEST=true` for development environments we add the htpasswd with the correct users otherwise we are not creating it.  Looks like we failed to remove the auth provider.

```
  oauthConfig.identityProvider[1].provider.file: Invalid value: "/etc/origin/master/htpasswd": could not read file: stat /etc/origin/master/htpasswd: no such file or directory
```

The question is, should we keep the `htpasswd` file when we are not putting users in it?  Should we remove the auth provider from `/etc/origin/master/master-config.yaml`?

@mjudeikis @kargakis @jim-minter Thoughts?
