### ISSUE TITLE
origin conformance failures in OSA

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#909]
There are 29 tests that failed in the last conformance run, they need to be triaged so we can know whether they flaked or they are broken in general or they are broken because of OSA-specific configuration. 
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/periodic-ci-openshift-openshift-azure-conformance/32
@jim-minter @mjudeikis @thekad 
/area tests
<details>

```
Summarizing 29 Failures:

[Fail] [Feature:Builds][pruning] prune builds based on settings in the buildconfig  [JustBeforeEach] should prune failed builds based on the failedBuildsHistoryLimit setting [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:52

[Fail] [Feature:Builds][pruning] prune builds based on settings in the buildconfig  [JustBeforeEach] should prune errored builds based on the failedBuildsHistoryLimit setting [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:52

[Fail] [Feature:Builds][Conformance] oc new-app  [JustBeforeEach] should fail with a --name longer than 58 characters [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/new_app.go:40

[Fail] [Feature:Builds][Conformance][valueFrom] process valueFrom in build strategy environment variables  [JustBeforeEach] should fail resolving unresolvable valueFrom in sti build environment variable references [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/valuefrom.go:48

[Fail] [Feature:Builds][Conformance] oc new-app  [JustBeforeEach] should succeed with a --name of 58 characters [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/new_app.go:40

[Fail] [Conformance][Area:Networking][Feature:Router] The HAProxy router [It] should set Forwarded headers appropriately [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/router/headers.go:79

[Fail] [image_ecosystem][mongodb] openshift mongodb image  creating from a template [It] should instantiate the template [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/util/framework.go:115

[Fail] [Feature:Builds][Conformance][valueFrom] process valueFrom in build strategy environment variables  [JustBeforeEach] should successfully resolve valueFrom in docker build environment variables [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/valuefrom.go:48

[Fail] [Feature:Builds][pruning] prune builds based on settings in the buildconfig  [JustBeforeEach] should prune builds after a buildConfig change [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:52

[Fail] [sig-network] Services [It] should be able to create a functioning NodePort service [Suite:openshift/conformance/parallel] [Suite:k8s] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/service_util.go:857

[Fail] [Conformance][templates] templateservicebroker bind test  [It] should pass bind tests [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_bind.go:115

[Fail] [Conformance][Area:Networking][Feature:Router] The HAProxy router [It] should respond with 503 to unrecognized hosts [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/util/url/url.go:70

[Fail] [Feature:Builds][pruning] prune builds based on settings in the buildconfig  [JustBeforeEach] [Conformance] buildconfigs should have a default history limit set when created via the group api [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:52

[Fail] [Area:Networking] multicast when using one of the plugins 'redhat/openshift-ovs-multitenant, redhat/openshift-ovs-networkpolicy' [It] should allow multicast traffic in namespaces where it is enabled [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/networking/multicast.go:51

[Fail] [Feature:Builds][Conformance][valueFrom] process valueFrom in build strategy environment variables  [JustBeforeEach] should successfully resolve valueFrom in s2i build environment variables [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/valuefrom.go:48

[Fail] [sig-network] Networking [It] should provide Internet connection for containers [Feature:Networking-IPv4] [Suite:openshift/conformance/parallel] [Suite:k8s] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/network/networking.go:50

[Fail] [Feature:Prometheus][Feature:Builds] Prometheus when installed on the cluster [It] should start and expose a secured proxy and verify build metrics [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/prometheus/prometheus_builds.go:180

[Fail] [Feature:Builds][pruning] prune builds based on settings in the buildconfig  [JustBeforeEach] should prune completed builds based on the successfulBuildsHistoryLimit setting [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:52

[Fail] [Conformance][templates] templateservicebroker end-to-end test  [It] should pass an end-to-end test [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_e2e.go:122

[Fail] [Feature:Builds][pruning] prune builds based on settings in the buildconfig  [JustBeforeEach] should prune canceled builds based on the failedBuildsHistoryLimit setting [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:52

[Fail] [Feature:Builds][Conformance][valueFrom] process valueFrom in build strategy environment variables  [JustBeforeEach] should fail resolving unresolvable valueFrom in docker build environment variable references [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/valuefrom.go:48

[Fail] [sig-cli] Kubectl client [k8s.io] Kubectl logs [It] should be able to retrieve and filter logs  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:1094

[Fail] [Conformance][Area:Networking][Feature:Router] The HAProxy router [It] should override the route host with a custom value [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/router/scoped.go:132

[Fail] [Feature:Builds][pruning] prune builds based on settings in the buildconfig  [JustBeforeEach] [Conformance] buildconfigs should not have a default history limit set when created via the legacy api [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/build_pruning.go:52

[Fail] [Feature:Builds] build with empty source  started build [It] should build even with an empty source in build config [Suite:openshift/conformance/parallel] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/nosrc.go:50

[Fail] [Feature:DeploymentConfig] deploymentconfigs rolled back [Conformance] [It] should rollback to an older deployment [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:872

[Fail] [Conformance][templates] templateservicebroker security test  [It] should pass security tests [Suite:openshift/conformance/parallel/minimal] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_security.go:96

[Fail] [sig-network] Services [It] should have session affinity work for NodePort service [Suite:openshift/conformance/parallel] [Suite:k8s] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/service_util.go:1490

[Fail] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] [It] should provide basic identity [Suite:openshift/conformance/parallel] [Suite:k8s] 
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:270

Ran 474 of 1268 Specs in 1893.135 seconds
FAIL! -- 445 Passed | 29 Failed | 0 Pending | 794 Skipped 
```
</details>

**Comment by mjudeikis** [comment]
I think the easiest way to triage for now would be to check previous runs (?)

**Comment by thekad** [comment]
that's actually really helpful @kargakis thanks

**Comment by kargakis** [comment]
@thekad I just realized there is one more flag missing `--target=[output:stable:azure-controllers]`. Updated the original command.

**Comment by thekad** [comment]
There's 2 big camps of failures here:

* "no route to host" errors, when the tests are trying to connect to the API, this also triggers another error "haproxy not forwarding the headers" due to the API not responding is my guess
* "failed to import imagestreams" most of these are in the form of "imagestreams.image.openshift.io \"wildfly\" not found". This probably also triggers another error "something tampered with image streams in the openshift namespace" (since it couldn't pull the image streams)

The first one looks like either the API router doesn't come up fully, or there is no network access to the API router. The second one might be a config issue?

**Comment by kwoodson** [comment]
To run the conformance test locally follow these steps:
1. Create a cluster `source ./env && ./hack/create.sh clusterfoo`
2. Download the origin test image from `docker pull registry.svc.ci.openshift.org/openshift/origin-v3.11:tests`
3. Run the following docker command:
```
docker run -it \
 -v $<PATH TO KUBECONFIG>/admin.kubeconfig:/usr/libexec/origin/admin.kubeconfig \
 -w /usr/libexec/origin \
 registry.svc.ci.openshift.org/openshift/origin-v3.11:tests bash
```
4. Run the test command:
```
KUBECONFIG=admin.kubeconfig ./ginkgo -v -noColor -nodes=1 ./extended.test --  -ginkgo.skip="\[local\]" \
  -e2e-output-dir /tmp/artifacts -report-dir /tmp/artifacts/junit -test.timeout=10m \
  -ginkgo.focus="\[Conformance\]\[Area\:Networking\]\[Feature\:Router\]\sThe\sHAProxy\srouter\sshould\sset\sForwarded\sheaders\sappropriately.*"
```

**Comment by kwoodson** [comment]
`[Conformance][Area:Networking][Feature:Router] The HAProxy router should set Forwarded headers appropriately`

This test fails because it assumes that the port 1936 is open on the router service.  Since OpenShift on Azure does not expose this port externally and because our router is of loadbalancer type, the curl to check the 1936 healthz port fails thus failing the test.

I attempted to open the port on the router service to see if it would fix this error.  The test continued to fail because the router added the X-Forwarded-For with an IP of 10.129.2.1 which is the tun0 IP and the test was looking for the IP of eth0 which is 10.0.0.6.  I’m unsure why the router appended the tun0 IP and the test pod was looking for the eth0 IP.  
```
Jan  8 20:14:35.181: Unexpected header: '10.129.2.1' (expected 10.0.0.6); All headers: http.Header{"X-Forwarded-Host":[]string{"router-headers.example.com"}, "X-Forwarded-Port":[]string{"80"}, "X-Forwarded-Proto":[]string{"http"}, "Forwarded":[]string{"for=10.129.2.1;host=router-headers.example.com;proto=http;proto-version="}, "X-Forwarded-For":[]string{"10.129.2.1"}, "User-Agent":[]string{"curl/7.61.0"}, "Accept":[]string{"*/*"}}
```
https://github.com/openshift/origin/blob/master/test/extended/router/headers.go

**Comment by kwoodson** [comment]
`[Conformance][templates] templateservicebroker bind test should pass bind tests`
```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/test/extended/templates/templateservicebroker_bind.go:107

    Expected error:
        <*url.Error | 0xc421a553b0>: {
            Op: "Put",
            URL: "https://172.30.21.39/brokers/template.openshift.io/v2/service_instances/aadda50d-d92c-402d-bd29-5ed2095aad2c/service_bindings/fc86614d-ddfe-4591-947e-41926f6cd57d",
            Err: {
                Op: "dial",
                Net: "tcp",
                Source: nil,
                Addr: {
                    IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 172, 30, 21, 39],
                    Port: 443,
                    Zone: "",
                },
                Err: {Syscall: "connect", Err: 0x6e},
            },
        }
        Put https://172.30.21.39/brokers/template.openshift.io/v2/service_instances/aadda50d-d92c-402d-bd29-5ed2095aad2c/service_bindings/fc86614d-ddfe-4591-947e-41926f6cd57d: dial tcp 172.30.21.39:443: connect: connection timed out
    not to have occurred
```
I'm unsure as to why this test is failing.  I believe it is due to an ipv6 to ipv4 as @Makdaam has recently pointed out.  It seems as though when fetching the service [here](https://github.com/openshift/origin/blob/release-3.11/test/extended/templates/templateservicebroker_bind.go#L108) the connection fails.  Further investigation is required to determine why the connection fails or why ipv6 to ipv4 nat is attempted.

**Comment by kwoodson** [comment]
`[Conformance][templates] templateinstance creation with invalid object reports error should report a failure on creation`

**Valid** test failure.  Requires a very recent version of 3.11.  The templateinstance that is created should not be ready because of an invalid name.

**Comment by kwoodson** [comment]
- `[Feature:Builds][Conformance] oc new-app should fail with a --name longer than 58 characters`
- ` [Feature:Builds][Conformance][valueFrom] process valueFrom in build strategy environment variables should fail resolving unresolvable valueFrom in docker build environment variable references`
- `[Feature:Builds][Conformance][valueFrom] process valueFrom in build strategy environment variables should fail resolving unresolvable valueFrom in sti build environment variable references `
- `[Feature:Builds][Conformance][valueFrom] process valueFrom in build strategy environment variables should successfully resolve valueFrom in docker build environment variables`
- `[Feature:Builds][Conformance][valueFrom] process valueFrom in build strategy environment variables should successfully resolve valueFrom in s2i build environment variables`
- `[Feature:Builds][pruning] prune builds based on settings in the buildconfig [Conformance] buildconfigs should have a default history limit set when created via the group api`
- `[Feature:Builds][pruning] prune builds based on settings in the buildconfig [Conformance] buildconfigs should not have a default history limit set when created via the legacy api`
- `[Feature:Builds][pruning] prune builds based on settings in the buildconfig should prune builds after a buildConfig change`
- `[Feature:Builds][pruning] prune builds based on settings in the buildconfig should prune canceled builds based on the failedBuildsHistoryLimit setting`
- `[Feature:Builds][pruning] prune builds based on settings in the buildconfig should prune completed builds based on the successfulBuildsHistoryLimit setting`
- `[Feature:Builds][pruning] prune builds based on settings in the buildconfig should prune errored builds based on the failedBuildsHistoryLimit setting`
- `[Feature:Builds][pruning] prune builds based on settings in the buildconfig should prune failed builds based on the failedBuildsHistoryLimit setting`
- `[Feature:Prometheus][Feature:Builds] Prometheus when installed on the cluster should start and expose a secured proxy and verify build metrics `

This list of tests are failing because they require the `wildfly` imagestream available in the `openshift` namespace. The tests start and verify the imagestreams are as expected before beginning the tests.  If an imagestream is missing then the tests do not actually proceed.

Notice that we do not have the `wildfly` imagestream [here](https://github.com/openshift/openshift-azure/tree/master/pkg/addons/data/ImageStream.image.openshift.io/openshift).  There is also not a corresponding RHEL `wildfly` imagestream located [here](https://github.com/openshift/origin/tree/master/examples/image-streams).

I attempted fixing this by using the centos wildfly imagestream and retested:
- `[Feature:Builds][Conformance][valueFrom] process valueFrom in build strategy environment variables should fail resolving unresolvable valueFrom in docker build environment variable references`
- `[Feature:Builds][pruning] prune builds based on settings in the buildconfig should prune completed builds based on the successfulBuildsHistoryLimit setting`

Both tests succeeded.  

**Action**: Find and create wildfly imagestream for RHEL or CentOS.

**Comment by kwoodson** [comment]
`[sig-network] Networking should provide Internet connection for containers`

This test attempts to ping `8.8.8.8`, `google.com`, etc.  This test fails as it runs on the compute node in the cluster.  This compute node runs behind a loadbalancer and does not have a public IP.  This scenario is explained here in scenario #2: https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#scenarios

**Comment by mgahagan73** [comment]
This commit on openshift/origin fixes the missing Wildfly image issue so we could update the testing container to include this commit if we do not want to include non-enterprise images. For the affected tests gathering all the container images for the various programming languages is a pre-flight test configuration issue so the image just needs to be present (or we need to not check for it as this patch does) I don't think any of the tests actually use Wildfly for anything.

commit 3bbf9fa955e8d2db0e9850b8c55e9618a5c22707
Author: gabemontero <gmontero@redhat.com>
Date:   Fri Jan 18 13:22:36 2019 -0500

    no longer validate existence of wildfly imagestream as part of switching openshift namespace samples to rhel
    
    https://jira.coreos.com/browse/DEVEXP-252

diff --git a/test/extended/util/framework.go b/test/extended/util/framework.go
index da6da4e796..9ec2789b45 100644
--- a/test/extended/util/framework.go
+++ b/test/extended/util/framework.go
@@ -53,7 +53,7 @@ const nfsPrefix = "nfs-"
 
 // WaitForOpenShiftNamespaceImageStreams waits for the standard set of imagestreams to be imported
 func WaitForOpenShiftNamespaceImageStreams(oc *CLI) error {
-       langs := []string{"ruby", "nodejs", "perl", "php", "python", "wildfly", "mysql", "postgresql", "mongodb", "jenkins"}
+       langs := []string{"ruby", "nodejs", "perl", "php", "python", "mysql", "postgresql", "mongodb", "jenkins"}
        scan := func() bool {
                for _, lang := range langs {
                        e2e.Logf("Checking language %v \n", lang)
@@ -96,7 +96,7 @@ func WaitForOpenShiftNamespaceImageStreams(oc *CLI) error {
 // imagestreams from the OpenShift namespace
 func CheckOpenShiftNamespaceImageStreams(oc *CLI) {
        missing := false
    https://jira.coreos.com/browse/DEVEXP-252

**Comment by mgahagan73** [comment]
Extended.[sig-api-machinery] Namespaces [Serial] should always delete fast (ALL of 100 namespaces in 150 seconds) [Feature:ComprehensiveNamespaceDraining] [Suite:openshift/conformance/serial] [Suite:k8s]
Extended.[sig-api-machinery] Namespaces [Serial] should delete fast enough (90 percent of 100 namespaces in 150 seconds) [Suite:openshift/conformance/serial] [Suite:k8s]

These two look like legitimate failures although I'm not sure we need to run both since there is a 10% difference between the two. We hit the timeout with about 33 images remaining.

**Comment by jim-minter** [comment]
AZURE-306
