### ISSUE TITLE
If create fails for some reason, update fails with "NodeDrainError" is VMSS does not exist

### ISSUE THREAD

**Issue by amanohar** [openshift/openshift-azure#993]
Sometimes update fails because of:

> Code=\"ParentResourceNotFound\" 
Message=\"Can not perform requested operation on nested resource. Parent resource 'ss-compute' not found.\"

In all cases this happens because create failed for some reason and then during update plugin tries to delete a non existent VMSS and this fails. Update operation should be handled idempotently whenever possible. E.g. in this case it means creating a new scale set based on goal state if the scale set does not exist.

**Comment by jim-minter** [comment]
@amanohar @sozercan please can you provide more context, I don't understand the issue.  What git commit are you seeing this on?

**Comment by jim-minter** [comment]
> sozercan [14:04]
looks like we are seeing this in prod `90c4effe` commit (and in INT which is private-preview-1.2 branch), happens during update when create failed for some reason (like quotaexceeded)
plugin tries to do an operation on a vm that doesn't exist
we are going to add a fail fast for quotaexceeded
Jim Minter [14:07]
if a create fails, I don't expect any further plugin operations to be carried out against the cluster.
also, all the update handling has been completely revamped since those commits - I'd rather the issue were raised against a newer version

**Comment by amanohar** [comment]
@jim-minter based on what you mention above: "all the update handling has been completely revamped since those commits" - let's close this and I will reopen with fresh context when needed.
